In [1]:
5/2

2.5

In [3]:
import pandas as pd

In [7]:
df_bookings = pd.read_csv('datasets/fact_bookings_clean.csv')
df_bookings

,booking_id,property_id,booking_date,check_in_date,checkout_date,no_guests,room_category,booking_platform,ratings_given,booking_status,revenue_generated,revenue_realized
0,May012216558RT12,16558,30-04-22,1/5/2022,2/5/2022,2.0,RT1,others,NaN,Cancelled,9100,3640
1,May012216558RT15,16558,27-04-22,1/5/2022,2/5/2022,4.0,RT1,direct online,5.0,Checked Out,10920,10920
2,May012216558RT16,16558,1/5/2022,1/5/2022,3/5/2022,2.0,RT1,others,4.0,Checked Out,9100,9100
3,May012216558RT17,16558,28-04-22,1/5/2022,6/5/2022,2.0,RT1,others,NaN,Cancelled,9100,3640
4,May012216558RT18,16558,26-04-22,1/5/2022,3/5/2022,2.0,RT1,logtrip,NaN,No Show,9100,9100
...,...,...,...,...,...,...,...,...,...,...,...,...
134568,Jul312217564RT45,17564,30-07-22,31-07-22,1/8/2022,2.0,RT4,others,2.0,Checked Out,32300,32300
134569,Jul312217564RT46,17564,29-07-22,31-07-22,3/8/2022,1.0,RT4,makeyourtrip,2.0,Checked Out,32300,32300
134570,Jul312217564RT48,17564,30-07-22,31-07-22,2/8/2022,1.0,RT4,tripster,NaN,Cancelled,32300,12920
134571,Jul312217564RT49,17564,29-07-22,31-07-22,1/8/2022,2.0,RT4,logtrip,2.0,Checked Out,32300,32300
134572,Jul312217564RT410,17564,31-07-22,31-07-22,1/8/2022,2.0,RT4,makeyourtrip,NaN,Cancelled,32300,12920

In [29]:
df_date = pd.read_csv('datasets/dim_date.csv')
df_hotels = pd.read_csv('datasets/dim_hotels.csv')
df_rooms = pd.read_csv('datasets/dim_rooms.csv')
df_aggr_bookings = pd.read_csv('datasets/fact_aggregated_bookings.csv')

In [10]:
df_aggr_bookings['occupancy_percentage %'] = round(((df_aggr_bookings['successful_bookings'] / df_aggr_bookings['capacity']) * 100),2)
df_aggr_bookings

,property_id,check_in_date,room_category,successful_bookings,capacity,occupancy_percentage %
0,16559,1-May-22,RT1,25,30.0,83.33
1,19562,1-May-22,RT1,28,30.0,93.33
2,19563,1-May-22,RT1,23,30.0,76.67
3,17558,1-May-22,RT1,30,19.0,157.89
4,16558,1-May-22,RT1,18,19.0,94.74
...,...,...,...,...,...,...
9195,16563,31-Jul-22,RT4,13,18.0,72.22
9196,16559,31-Jul-22,RT4,13,18.0,72.22
9197,17558,31-Jul-22,RT4,3,6.0,50.00
9198,19563,31-Jul-22,RT4,3,6.0,50.00
9199,17561,31-Jul-22,RT4,3,4.0,75.00

In [30]:
df_date

         date  mmm yy week no  day_type
0   01-May-22  May 22    W 19   weekend
1   02-May-22  May 22    W 19  weekeday
2   03-May-22  May 22    W 19  weekeday
3   04-May-22  May 22    W 19  weekeday
4   05-May-22  May 22    W 19  weekeday
..        ...     ...     ...       ...
87  27-Jul-22  Jul 22    W 31  weekeday
88  28-Jul-22  Jul 22    W 31  weekeday
89  29-Jul-22  Jul 22    W 31  weekeday
90  30-Jul-22  Jul 22    W 31   weekend
91  31-Jul-22  Jul 22    W 32   weekend

[92 rows x 4 columns]

In [31]:
df_date.dtypes

date        str
mmm yy      str
week no     str
day_type    str
dtype: object

In [32]:
df_date['day_type'] = df_date['day_type'].replace('weekeday','weekday')
df_date

         date  mmm yy week no day_type
0   01-May-22  May 22    W 19  weekend
1   02-May-22  May 22    W 19  weekday
2   03-May-22  May 22    W 19  weekday
3   04-May-22  May 22    W 19  weekday
4   05-May-22  May 22    W 19  weekday
..        ...     ...     ...      ...
87  27-Jul-22  Jul 22    W 31  weekday
88  28-Jul-22  Jul 22    W 31  weekday
89  29-Jul-22  Jul 22    W 31  weekday
90  30-Jul-22  Jul 22    W 31  weekend
91  31-Jul-22  Jul 22    W 32  weekend

[92 rows x 4 columns]

In [33]:
df_date['date'] = pd.to_datetime(df_date['date'])
df_date

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_5600\2310970186.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_date['date'] = pd.to_datetime(df_date['date'])

         date  mmm yy week no day_type
0  2022-05-01  May 22    W 19  weekend
1  2022-05-02  May 22    W 19  weekday
2  2022-05-03  May 22    W 19  weekday
3  2022-05-04  May 22    W 19  weekday
4  2022-05-05  May 22    W 19  weekday
..        ...     ...     ...      ...
87 2022-07-27  Jul 22    W 31  weekday
88 2022-07-28  Jul 22    W 31  weekday
89 2022-07-29  Jul 22    W 31  weekday
90 2022-07-30  Jul 22    W 31  weekend
91 2022-07-31  Jul 22    W 32  weekend

[92 rows x 4 columns]

In [34]:
df_date['month'] = df_date['date'].dt.strftime('%b')
df_date['year'] = df_date['date'].dt.year
df_date['week_no'] = 'W ' + df_date['date'].dt.isocalendar().week.astype(str)
df_date

         date  mmm yy week no day_type month  year week_no
0  2022-05-01  May 22    W 19  weekend   May  2022    W 17
1  2022-05-02  May 22    W 19  weekday   May  2022    W 18
2  2022-05-03  May 22    W 19  weekday   May  2022    W 18
3  2022-05-04  May 22    W 19  weekday   May  2022    W 18
4  2022-05-05  May 22    W 19  weekday   May  2022    W 18
..        ...     ...     ...      ...   ...   ...     ...
87 2022-07-27  Jul 22    W 31  weekday   Jul  2022    W 30
88 2022-07-28  Jul 22    W 31  weekday   Jul  2022    W 30
89 2022-07-29  Jul 22    W 31  weekday   Jul  2022    W 30
90 2022-07-30  Jul 22    W 31  weekend   Jul  2022    W 30
91 2022-07-31  Jul 22    W 32  weekend   Jul  2022    W 30

[92 rows x 7 columns]

In [35]:
df_date

         date  mmm yy week no day_type month  year week_no
0  2022-05-01  May 22    W 19  weekend   May  2022    W 17
1  2022-05-02  May 22    W 19  weekday   May  2022    W 18
2  2022-05-03  May 22    W 19  weekday   May  2022    W 18
3  2022-05-04  May 22    W 19  weekday   May  2022    W 18
4  2022-05-05  May 22    W 19  weekday   May  2022    W 18
..        ...     ...     ...      ...   ...   ...     ...
87 2022-07-27  Jul 22    W 31  weekday   Jul  2022    W 30
88 2022-07-28  Jul 22    W 31  weekday   Jul  2022    W 30
89 2022-07-29  Jul 22    W 31  weekday   Jul  2022    W 30
90 2022-07-30  Jul 22    W 31  weekend   Jul  2022    W 30
91 2022-07-31  Jul 22    W 32  weekend   Jul  2022    W 30

[92 rows x 7 columns]

In [36]:
df_date.drop('mmm yy', axis=1, inplace=True)

In [38]:
df_date.to_csv('datasets/dim_dates_clean.csv')

In [39]:
df_hotels

    property_id  property_name  category       city
0         16558   Atliq Grands    Luxury      Delhi
1         16559  Atliq Exotica    Luxury     Mumbai
2         16560     Atliq City  Business      Delhi
3         16561      Atliq Blu    Luxury      Delhi
4         16562      Atliq Bay    Luxury      Delhi
5         16563   Atliq Palace  Business      Delhi
6         17558   Atliq Grands    Luxury     Mumbai
7         17559  Atliq Exotica    Luxury     Mumbai
8         17560     Atliq City  Business     Mumbai
9         17561      Atliq Blu    Luxury     Mumbai
10        17562      Atliq Bay    Luxury     Mumbai
11        17563   Atliq Palace  Business     Mumbai
12        18558   Atliq Grands    Luxury  Hyderabad
13        18559  Atliq Exotica    Luxury  Hyderabad
14        18560     Atliq City  Business  Hyderabad
15        18561      Atliq Blu    Luxury  Hyderabad
16        18562      Atliq Bay    Luxury  Hyderabad
17        18563   Atliq Palace  Business  Hyderabad
18        19558   Atliq Grands    Luxury  Bangalore
19        19559  Atliq Exotica    Luxury  Bangalore
20        19560     Atliq City  Business  Bangalore
21        19561      Atliq Blu    Luxury  Bangalore
22        19562      Atliq Bay    Luxury  Bangalore
23        19563   Atliq Palace  Business  Bangalore
24        17564  Atliq Seasons  Business     Mumbai

In [40]:
df_rooms

  room_id    room_class
0     RT1      Standard
1     RT2         Elite
2     RT3       Premium
3     RT4  Presidential