In [1]:
import csv

In [32]:
def calculate_rating_stats(data,industry=None):
    rating = []
    for row in data:
        if row[3]!= 'NULL' and (not industry or row[1]==industry):
            rating.append(float(row[3]))
    max_rating = max(rating)
    min_rating = min(rating)
    avg_rating = sum(rating) / len(rating)
    return max_rating, min_rating, avg_rating

In [28]:
calculate_rating_stats(data)

[8.3, 7.0, 6.8, 7.9, 6.8, 9.3, 8.6, 8.0, 8.5, 7.9, 8.6, 7.8, 9.2, 9.0, 9.0, 8.2, 8.5, 8.4, 8.4, 6.9, 7.8, 8.0, 8.4, 7.4, 7.2, 8.3, 8.1, 8.1, 8.3, 8.1, 1.9, 8.4, 8.4, 7.6, 8.0, 8.0]

(9.3, 1.9, 7.919444444444445)

In [29]:
with open("movies.csv") as f:
    data = list(csv.reader(f))
    print(data)
    header = data[0]
    data = data[1:]
data

[['title', 'industry', 'release_year', 'imdb_rating', 'studio', 'budget', 'revenue', 'unit', 'currency', 'language'], ['Pather Panchali', 'Bollywood', '1955', '8.3', 'Government of West Bengal', '70000', '100000', 'Thousands', 'INR', 'Bengali'], ['Doctor Strange in the Multiverse of Madness', 'Hollywood', '2022', '7', 'Marvel Studios', '200', '954.8', 'Millions', 'USD', 'English'], ['Thor: The Dark World ', 'Hollywood', '2013', '6.8', 'Marvel Studios', '165', '644.8', 'Millions', 'USD', 'English'], ['Thor: Ragnarok ', 'Hollywood', '2017', '7.9', 'Marvel Studios', '180', '854', 'Millions', 'USD', 'English'], ['Thor: Love and Thunder ', 'Hollywood', '2022', '6.8', 'Marvel Studios', '250', '670', 'Millions', 'USD', 'English'], ['The Shawshank Redemption', 'Hollywood', '1994', '9.3', 'Castle Rock Entertainment', '25', '73.3', 'Millions', 'USD', 'English'], ['Interstellar', 'Hollywood', '2014', '8.6', 'Warner Bros. Pictures', '165', '701.8', 'Millions', 'USD', 'English'], ['The Pursuit of Happyness', 'Hollywood', '2006', '8', 'Columbia Pictures', '55', '307.1', 'Millions', 'USD', 'English'], ['Gladiator', 'Hollywood', '2000', '8.5', 'Universal Pictures  ', '103', '460.5', 'Millions', 'USD', 'English'], ['Titanic', 'Hollywood', '1997', '7.9', 'Paramount Pictures', '200', '2202', 'Millions', 'USD', 'English'], ["It's a Wonderful Life", 'Hollywood', '1946', '8.6', 'Liberty Films', '3.18', '3.3', 'Millions', 'USD', 'English'], ['Avatar', 'Hollywood', '2009', '7.8', '20th Century Fox', '237', '2847', 'Millions', 'USD', 'English'], ['The Godfather', 'Hollywood', '1972', '9.2', 'Paramount Pictures', '7.2', '291', 'Millions', 'USD', 'English'], ['The Dark Knight', 'Hollywood', '2008', '9', 'Syncopy', '185', '1006', 'Millions', 'USD', 'English'], ["Schindler's List", 'Hollywood', '1993', '9', 'Universal Pictures', '22', '322.2', 'Millions', 'USD', 'English'], ['Jurassic Park', 'Hollywood', '1993', '8.2', 'Universal Pictures', '63', '1046', 'Millions', 'USD', 'English'], ['Parasite', 'Hollywood', '2019', '8.5', '', '15.5', '263.1', 'Millions', 'USD', 'English'], ['Avengers: Endgame', 'Hollywood', '2019', '8.4', 'Marvel Studios', '400', '2798', 'Millions', 'USD', 'English'], ['Avengers: Infinity War', 'Hollywood', '2018', '8.4', 'Marvel Studios', '400', '2048', 'Millions', 'USD', 'English'], ['Captain America: The First Avenger', 'Hollywood', '2011', '6.9', 'Marvel Studios', '216.7', '370.6', 'Millions', 'USD', 'English'], ['Captain America: The Winter Soldier', 'Hollywood', '2014', '7.8', 'Marvel Studios', '177', '714.4', 'Millions', 'USD', 'English'], ['Dilwale Dulhania Le Jayenge', 'Bollywood', '1995', '8', 'Yash Raj Films', '400', '2000', 'Millions', 'INR', 'Hindi'], ['3 Idiots', 'Bollywood', '2009', '8.4', 'Vinod Chopra Films', '550', '4000', 'Millions', 'INR', 'Hindi'], ['Kabhi Khushi Kabhie Gham', 'Bollywood', '2001', '7.4', 'Dharma Productions', '390', '1360', 'Millions', 'INR', 'Hindi'], ['Bajirao Mastani ', 'Bollywood', '2015', '7.2', '', '1.4', '3.5', 'Billions', 'INR', 'Hindi'], ['Taare Zameen Par', 'Bollywood', '2007', '8.3', '', '120', '1350', 'Millions', 'INR', 'Hindi'], ['Munna Bhai M.B.B.S.', 'Bollywood', '2003', '8.1', 'Vinod Chopra Productions', '100', '410', 'Millions', 'INR', 'Hindi'], ['PK', 'Bollywood', '2014', '8.1', 'Vinod Chopra Films', '850', '8540', 'Millions', 'INR', 'Hindi'], ['Sanju', 'Bollywood', '2018', 'NULL', 'Vinod Chopra Films', '1', '5.9', 'Billions', 'INR', 'Hindi'], ['The Kashmir Files', 'Bollywood', '2022', '8.3', 'Zee Studios', '250', '3409', 'Millions', 'INR', 'Hindi'], ['Bajrangi Bhaijaan', 'Bollywood', '2015', '8.1', 'Salman Khan Films', '900', '11690', 'Millions', 'INR', 'Hindi'], ['Race 3', 'Bollywood', '2018', '1.9', 'Salman Khan Films', '1.8', '3.1', 'Billions', 'INR', 'Hindi'], ['Shershaah', 'Bollywood', '2021', '8.4', 'Dharma Productions', '500', '950', 'Millions', 'INR', 'Hindi'], ['K.G.F: Chapter 2', 'Bollywood', '2022', '8.4', 'Hombale Films', '1', '12.5', 'Billions', 'INR', 'Kannada'], ['Pushpa: The Rise - Part 1', 'Bollywood', '2021', '7.6', 'Mythri Movie Makers', '2', '3.6', 'Billions', 'INR', 'Telugu'], ['RRR', 'Bollywood', '2022', '8', 'DVV Entertainment', '5.5', '12', 'Billions', 'INR', 'Telugu'], ['Baahubali: The Beginning', 'Bollywood', '2015', '8', 'Arka Media Works', '1.8', '6.5', 'Billions', 'INR', 'Telugu']]

[['Pather Panchali',
  'Bollywood',
  '1955',
  '8.3',
  'Government of West Bengal',
  '70000',
  '100000',
  'Thousands',
  'INR',
  'Bengali'],
 ['Doctor Strange in the Multiverse of Madness',
  'Hollywood',
  '2022',
  '7',
  'Marvel Studios',
  '200',
  '954.8',
  'Millions',
  'USD',
  'English'],
 ['Thor: The Dark World ',
  'Hollywood',
  '2013',
  '6.8',
  'Marvel Studios',
  '165',
  '644.8',
  'Millions',
  'USD',
  'English'],
 ['Thor: Ragnarok ',
  'Hollywood',
  '2017',
  '7.9',
  'Marvel Studios',
  '180',
  '854',
  'Millions',
  'USD',
  'English'],
 ['Thor: Love and Thunder ',
  'Hollywood',
  '2022',
  '6.8',
  'Marvel Studios',
  '250',
  '670',
  'Millions',
  'USD',
  'English'],
 ['The Shawshank Redemption',
  'Hollywood',
  '1994',
  '9.3',
  'Castle Rock Entertainment',
  '25',
  '73.3',
  'Millions',
  'USD',
  'English'],
 ['Interstellar',
  'Hollywood',
  '2014',
  '8.6',
  'Warner Bros. Pictures',
  '165',
  '701.8',
  'Millions',
  'USD',
  'English'],
 ['The Pursuit of Happyness',
  'Hollywood',
  '2006',
  '8',
  'Columbia Pictures',
  '55',
  '307.1',
  'Millions',
  'USD',
  'English'],
 ['Gladiator',
  'Hollywood',
  '2000',
  '8.5',
  'Universal Pictures  ',
  '103',
  '460.5',
  'Millions',
  'USD',
  'English'],
 ['Titanic',
  'Hollywood',
  '1997',
  '7.9',
  'Paramount Pictures',
  '200',
  '2202',
  'Millions',
  'USD',
  'English'],
 ["It's a Wonderful Life",
  'Hollywood',
  '1946',
  '8.6',
  'Liberty Films',
  '3.18',
  '3.3',
  'Millions',
  'USD',
  'English'],
 ['Avatar',
  'Hollywood',
  '2009',
  '7.8',
  '20th Century Fox',
  '237',
  '2847',
  'Millions',
  'USD',
  'English'],
 ['The Godfather',
  'Hollywood',
  '1972',
  '9.2',
  'Paramount Pictures',
  '7.2',
  '291',
  'Millions',
  'USD',
  'English'],
 ['The Dark Knight',
  'Hollywood',
  '2008',
  '9',
  'Syncopy',
  '185',
  '1006',
  'Millions',
  'USD',
  'English'],
 ["Schindler's List",
  'Hollywood',
  '1993',
  '9',
  'Universal Pictures',
  '22',
  '322.2',
  'Millions',
  'USD',
  'English'],
 ['Jurassic Park',
  'Hollywood',
  '1993',
  '8.2',
  'Universal Pictures',
  '63',
  '1046',
  'Millions',
  'USD',
  'English'],
 ['Parasite',
  'Hollywood',
  '2019',
  '8.5',
  '',
  '15.5',
  '263.1',
  'Millions',
  'USD',
  'English'],
 ['Avengers: Endgame',
  'Hollywood',
  '2019',
  '8.4',
  'Marvel Studios',
  '400',
  '2798',
  'Millions',
  'USD',
  'English'],
 ['Avengers: Infinity War',
  'Hollywood',
  '2018',
  '8.4',
  'Marvel Studios',
  '400',
  '2048',
  'Millions',
  'USD',
  'English'],
 ['Captain America: The First Avenger',
  'Hollywood',
  '2011',
  '6.9',
  'Marvel Studios',
  '216.7',
  '370.6',
  'Millions',
  'USD',
  'English'],
 ['Captain America: The Winter Soldier',
  'Hollywood',
  '2014',
  '7.8',
  'Marvel Studios',
  '177',
  '714.4',
  'Millions',
  'USD',
  'English'],
 ['Dilwale Dulhania Le Jayenge',
  'Bollywood',
  '1995',
  '8',
  'Yash Raj Films',
  '400',
  '2000',
  'Millions',
  'INR',
  'Hindi'],
 ['3 Idiots',
  'Bollywood',
  '2009',
  '8.4',
  'Vinod Chopra Films',
  '550',
  '4000',
  'Millions',
  'INR',
  'Hindi'],
 ['Kabhi Khushi Kabhie Gham',
  'Bollywood',
  '2001',
  '7.4',
  'Dharma Productions',
  '390',
  '1360',
  'Millions',
  'INR',
  'Hindi'],
 ['Bajirao Mastani ',
  'Bollywood',
  '2015',
  '7.2',
  '',
  '1.4',
  '3.5',
  'Billions',
  'INR',
  'Hindi'],
 ['Taare Zameen Par',
  'Bollywood',
  '2007',
  '8.3',
  '',
  '120',
  '1350',
  'Millions',
  'INR',
  'Hindi'],
 ['Munna Bhai M.B.B.S.',
  'Bollywood',
  '2003',
  '8.1',
  'Vinod Chopra Productions',
  '100',
  '410',
  'Millions',
  'INR',
  'Hindi'],
 ['PK',
  'Bollywood',
  '2014',
  '8.1',
  'Vinod Chopra Films',
  '850',
  '8540',
  'Millions',
  'INR',
  'Hindi'],
 ['Sanju',
  'Bollywood',
  '2018',
  'NULL',
  'Vinod Chopra Films',
  '1',
  '5.9',
  'Billions',
  'INR',
  'Hindi'],
 ['The Kashmir Files',
  'Bollywood',
  '2022',
  '8.3',
  'Zee Studios',
  '250',
  '3409',
  'Millions',
  'INR',
  'Hindi'],
 ['Bajrangi Bhaijaan',
  'Bollywood',
  '2015',
  '8.1',
  'Salman Khan Films',
  '900',
  '11690',
  'Millions',
  'INR',
  'Hindi'],
 ['Race 3',
  'Bollywood',
  '2018',
  '1.9',
  'Salman Khan Films',
  '1.8',
  '3.1',
  'Billions',
  'INR',
  'Hindi'],
 ['Shershaah',
  'Bollywood',
  '2021',
  '8.4',
  'Dharma Productions',
  '500',
  '950',
  'Millions',
  'INR',
  'Hindi'],
 ['K.G.F: Chapter 2',
  'Bollywood',
  '2022',
  '8.4',
  'Hombale Films',
  '1',
  '12.5',
  'Billions',
  'INR',
  'Kannada'],
 ['Pushpa: The Rise - Part 1',
  'Bollywood',
  '2021',
  '7.6',
  'Mythri Movie Makers',
  '2',
  '3.6',
  'Billions',
  'INR',
  'Telugu'],
 ['RRR',
  'Bollywood',
  '2022',
  '8',
  'DVV Entertainment',
  '5.5',
  '12',
  'Billions',
  'INR',
  'Telugu'],
 ['Baahubali: The Beginning',
  'Bollywood',
  '2015',
  '8',
  'Arka Media Works',
  '1.8',
  '6.5',
  'Billions',
  'INR',
  'Telugu']]

In [33]:
max_rating, min_rating, avg_rating = calculate_rating_stats(data)
print(f"All records: \nMIN rating: {min_rating}\nMAX rating: {max_rating}\nAVG rating: {avg_rating}")

max_rating, min_rating, avg_rating = calculate_rating_stats(data,industry="Bollywood")
print(f"BOLLYWOOD records: \nMIN rating: {min_rating}\nMAX rating: {max_rating}\nAVG rating: {avg_rating}")

max_rating, min_rating, avg_rating = calculate_rating_stats(data,industry="Hollywood")
print(f"HOLLYWOOD records: \nMIN rating: {min_rating}\nMAX rating: {max_rating}\nAVG rating: {avg_rating}")

All records:
MIN rating: 1.9
MAX rating: 9.3
AVG rating: 7.919444444444445
BOLLYWOOD records:
MIN rating: 1.9
MAX rating: 8.4
AVG rating: 7.65625
HOLLYWOOD records:
MIN rating: 6.8
MAX rating: 9.3
AVG rating: 8.129999999999999

In [34]:
# to install pandas
! pip install pandas

Requirement already satisfied: pandas in E:\padhai ka saman\codebasic\Python\.venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in E:\padhai ka saman\codebasic\Python\.venv\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in E:\padhai ka saman\codebasic\Python\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in E:\padhai ka saman\codebasic\Python\.venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in E:\padhai ka saman\codebasic\Python\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [35]:
import pandas as pd

In [ ]:
df = pd.read_csv("movies.csv")

# rows from the start
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English

In [ ]:
# rows from the end
df.tail()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.0,950.0,Millions,INR,Hindi
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.0,12.5,Billions,INR,Kannada
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.0,3.6,Billions,INR,Telugu
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.5,12.0,Billions,INR,Telugu
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.8,6.5,Billions,INR,Telugu

In [46]:
# random rows
df.sample(3)

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
27,PK,Bollywood,2014,8.1,Vinod Chopra Films,850.0,8540.0,Millions,INR,Hindi
29,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,250.0,3409.0,Millions,INR,Hindi
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.0,2048.0,Millions,USD,English

In [ ]:
# row 2 to 6 just like python list
df[2:7]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English
6,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,165.0,701.8,Millions,USD,English

In [56]:
df.shape

(37, 10)

In [57]:
df['imdb_rating']

0     8.3
1     7.0
2     6.8
3     7.9
4     6.8
5     9.3
6     8.6
7     8.0
8     8.5
9     7.9
10    8.6
11    7.8
12    9.2
13    9.0
14    9.0
15    8.2
16    8.5
17    8.4
18    8.4
19    6.9
20    7.8
21    8.0
22    8.4
23    7.4
24    7.2
25    8.3
26    8.1
27    8.1
28    NaN
29    8.3
30    8.1
31    1.9
32    8.4
33    8.4
34    7.6
35    8.0
36    8.0
Name: imdb_rating, dtype: float64

In [ ]:
# part of df only but a single column --> 1-dim data structure
type(df.imdb_rating)

pandas.Series

In [ ]:
# Entire spreadsheet --> 2-dim table structure
type(df)

pandas.DataFrame

In [60]:
df['imdb_rating'].mean()

np.float64(7.919444444444445)

In [65]:
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append_internal',
 '_arith_method',
 '_arith_method_with_reindex',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_copy_deprecation',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_label_or_level_ambiguity',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_module_source',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_sanitize_column',
 '_select_dtypes_indices',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'between_time',
 'bfill',
 'boxplot',
 'budget',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'currency',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'imdb_rating',
 'index',
 'industry',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'language',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'release_year',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'revenue',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'studio',
 'style',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'title',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_hdf',
 'to_html',
 'to_iceberg',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unit',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [68]:
df[df['industry'] == "Bollywood"]['imdb_rating'].mean()

np.float64(7.656250000000001)

In [70]:
df[df['industry'] == "Hollywood"]['imdb_rating'].mean()

np.float64(8.130000000000003)

In [71]:
df_h = df[df['industry'] == 'Hollywood']
df_b = df[df['industry'] == 'Bollywood']

In [72]:
df_h.imdb_rating.mean() , df_h.imdb_rating.max(), df_h.imdb_rating.min()

(np.float64(8.130000000000003), np.float64(9.3), np.float64(6.8))

In [73]:
df_b.imdb_rating.mean(), df_b.imdb_rating.max(), df_b.imdb_rating.min()

(np.float64(7.656250000000001), np.float64(8.4), np.float64(1.9))

In [79]:
df["industry"].unique()

<StringArray>
['Bollywood', 'Hollywood']
Length: 2, dtype: str

In [88]:
print(df.language.unique())
print(df.language.value_counts().unique())

<StringArray>
['Bengali', 'English', 'Hindi', 'Kannada', 'Telugu']
Length: 5, dtype: str
[20 12  3  1]

In [94]:
df.language.value_counts()

language
English    20
Hindi      12
Telugu      3
Bengali     1
Kannada     1
Name: count, dtype: int64

In [99]:
a = df[["title","imdb_rating","industry"]]
a.head()

                                         title  imdb_rating   industry
0                              Pather Panchali          8.3  Bollywood
1  Doctor Strange in the Multiverse of Madness          7.0  Hollywood
2                        Thor: The Dark World           6.8  Hollywood
3                              Thor: Ragnarok           7.9  Hollywood
4                      Thor: Love and Thunder           6.8  Hollywood

In [106]:
df.head()
df[(df.release_year >= 2000) & (df.release_year <= 2010) ]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.0,307.1,Millions,USD,English
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.0,460.5,Millions,USD,English
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.0,2847.0,Millions,USD,English
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.0,1006.0,Millions,USD,English
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.0,4000.0,Millions,INR,Hindi
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.0,1360.0,Millions,INR,Hindi
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.0,1350.0,Millions,INR,Hindi
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.0,410.0,Millions,INR,Hindi

In [110]:
df[df["studio"] == "Marvel Studios"]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.0,2798.0,Millions,USD,English
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.0,2048.0,Millions,USD,English
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.7,370.6,Millions,USD,English
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.0,714.4,Millions,USD,English

In [111]:
df.describe()

       release_year  imdb_rating        budget        revenue
count     37.000000    36.000000     37.000000      37.000000
mean    2007.027027     7.919444   2084.975135    4117.135135
std       17.657995     1.204947  11477.487145   16372.462682
min     1946.000000     1.900000      1.000000       3.100000
25%     2001.000000     7.800000     15.500000     263.100000
50%     2014.000000     8.100000    165.000000     701.800000
75%     2018.000000     8.400000    250.000000    2000.000000
max     2022.000000     9.300000  70000.000000  100000.000000

In [112]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         37 non-null     str
 1   industry      37 non-null     str
 2   release_year  37 non-null     int64
 3   imdb_rating   36 non-null     float64
 4   studio        34 non-null     str
 5   budget        37 non-null     float64
 6   revenue       37 non-null     float64
 7   unit          37 non-null     str
 8   currency      37 non-null     str
 9   language      37 non-null     str
dtypes: float64(3), int64(1), str(6)
memory usage: 3.0 KB

In [118]:
df[(df.imdb_rating == df.imdb_rating.max()) | (df.imdb_rating == df.imdb_rating.min())]['title']

5     The Shawshank Redemption
31                      Race 3
Name: title, dtype: str

In [126]:
import time

df['movie_age'] = df['release_year'].apply(lambda x: time.localtime().tm_year - x )
df['movie_age']

0     71
1      4
2     13
3      9
4      4
5     32
6     12
7     20
8     26
9     29
10    80
11    17
12    54
13    18
14    33
15    33
16     7
17     7
18     8
19    15
20    12
21    31
22    17
23    25
24    11
25    19
26    23
27    12
28     8
29     4
30    11
31     8
32     5
33     4
34     5
35     4
36    11
Name: movie_age, dtype: int64

In [129]:
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,movie_age
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,71
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,4
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,13
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,9
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,4

In [131]:
df['profit'] = df['revenue'] - df['budget']
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,movie_age,profit
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,71,30000.0
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,4,754.8
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,13,479.8
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,9,674.0
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,4,420.0

In [134]:
df['profit'] = df.apply(lambda x : x['revenue'] - x['budget'], axis=1)
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,movie_age,profit
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,71,30000.0
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,4,754.8
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,13,479.8
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,9,674.0
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,4,420.0

In [135]:
df.index

RangeIndex(start=0, stop=37, step=1)

In [136]:
df.set_index("title")

,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,movie_age,profit
title,,,,,,,,,,,
Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.00,100000.0,Thousands,INR,Bengali,71,30000.00
Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.00,954.8,Millions,USD,English,4,754.80
Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.00,644.8,Millions,USD,English,13,479.80
Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.00,854.0,Millions,USD,English,9,674.00
Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.00,670.0,Millions,USD,English,4,420.00
The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.00,73.3,Millions,USD,English,32,48.30
Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,165.00,701.8,Millions,USD,English,12,536.80
The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.00,307.1,Millions,USD,English,20,252.10
Gladiator,Hollywood,2000,8.5,Universal Pictures,103.00,460.5,Millions,USD,English,26,357.50
Titanic,Hollywood,1997,7.9,Paramount Pictures,200.00,2202.0,Millions,USD,English,29,2002.00
It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English,80,0.12
Avatar,Hollywood,2009,7.8,20th Century Fox,237.00,2847.0,Millions,USD,English,17,2610.00
The Godfather,Hollywood,1972,9.2,Paramount Pictures,7.20,291.0,Millions,USD,English,54,283.80
The Dark Knight,Hollywood,2008,9.0,Syncopy,185.00,1006.0,Millions,USD,English,18,821.00
Schindler's List,Hollywood,1993,9.0,Universal Pictures,22.00,322.2,Millions,USD,English,33,300.20
Jurassic Park,Hollywood,1993,8.2,Universal Pictures,63.00,1046.0,Millions,USD,English,33,983.00
Parasite,Hollywood,2019,8.5,NaN,15.50,263.1,Millions,USD,English,7,247.60
Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.00,2798.0,Millions,USD,English,7,2398.00
Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.00,2048.0,Millions,USD,English,8,1648.00
Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.70,370.6,Millions,USD,English,15,153.90
Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.00,714.4,Millions,USD,English,12,537.40
Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,400.00,2000.0,Millions,INR,Hindi,31,1600.00
3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.00,4000.0,Millions,INR,Hindi,17,3450.00
Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.00,1360.0,Millions,INR,Hindi,25,970.00
Bajirao Mastani,Bollywood,2015,7.2,NaN,1.40,3.5,Billions,INR,Hindi,11,2.10
Taare Zameen Par,Bollywood,2007,8.3,NaN,120.00,1350.0,Millions,INR,Hindi,19,1230.00
Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.00,410.0,Millions,INR,Hindi,23,310.00
PK,Bollywood,2014,8.1,Vinod Chopra Films,850.00,8540.0,Millions,INR,Hindi,12,7690.00
Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1.00,5.9,Billions,INR,Hindi,8,4.90
The Kashmir Files,Bollywood,2022,8.3,Zee Studios,250.00,3409.0,Millions,INR,Hindi,4,3159.00
Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,900.00,11690.0,Millions,INR,Hindi,11,10790.00
Race 3,Bollywood,2018,1.9,Salman Khan Films,1.80,3.1,Billions,INR,Hindi,8,1.30
Shershaah,Bollywood,2021,8.4,Dharma Productions,500.00,950.0,Millions,INR,Hindi,5,450.00
K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.00,12.5,Billions,INR,Kannada,4,11.50
Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.00,3.6,Billions,INR,Telugu,5,1.60
RRR,Bollywood,2022,8.0,DVV Entertainment,5.50,12.0,Billions,INR,Telugu,4,6.50
Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.80,6.5,Billions,INR,Telugu,11,4.70

In [139]:
df.loc[0]

title                     Pather Panchali
industry                        Bollywood
release_year                         1955
imdb_rating                           8.3
studio          Government of West Bengal
budget                            70000.0
revenue                          100000.0
unit                            Thousands
currency                              INR
language                          Bengali
movie_age                              71
profit                            30000.0
Name: 0, dtype: object

In [141]:
df.loc[[0,1]]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,movie_age,profit
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,71,30000.0
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,4,754.8

In [145]:
df.iloc[2:10]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,movie_age,profit
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,13,479.8
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,9,674.0
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,4,420.0
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English,32,48.3
6,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,165.0,701.8,Millions,USD,English,12,536.8
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.0,307.1,Millions,USD,English,20,252.1
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.0,460.5,Millions,USD,English,26,357.5
9,Titanic,Hollywood,1997,7.9,Paramount Pictures,200.0,2202.0,Millions,USD,English,29,2002.0