In [2]:
import pandas as pd

In [4]:
df_ind = pd.DataFrame({
    'city':['Mumbai','Delhi','Bangalore'],
    'temperature':[32,45,30],
    'humidity':[80,60,78]
})
df_ind

        city  temperature  humidity
0     Mumbai           32        80
1      Delhi           45        60
2  Bangalore           30        78

In [5]:
df_us = pd.DataFrame({
    'city':['New York','Orlando','Chicago'],
    'temperature':[21,14,35],
    'humidity':[68,65,75]
})
df_us

       city  temperature  humidity
0  New York           21        68
1   Orlando           14        65
2   Chicago           35        75

In [8]:
df = pd.concat([df_ind,df_us], keys=['india','us'])
df

              city  temperature  humidity
india 0     Mumbai           32        80
      1      Delhi           45        60
      2  Bangalore           30        78
us    0   New York           21        68
      1    Orlando           14        65
      2    Chicago           35        75

In [11]:
df.loc['india']

        city  temperature  humidity
0     Mumbai           32        80
1      Delhi           45        60
2  Bangalore           30        78

In [13]:
temperature_df = df_ind[['city','temperature']]
temperature_df

        city  temperature
0     Mumbai           32
1      Delhi           45
2  Bangalore           30

In [14]:
windspeed_df = pd.DataFrame({
    'city': ['Delhi','Mumbai'],
    'windspeed':[7,12]
}, index=[1,0])
windspeed_df

     city  windspeed
1   Delhi          7
0  Mumbai         12

In [17]:
pd.concat([temperature_df,windspeed_df], axis=1)

        city  temperature    city  windspeed
0     Mumbai           32  Mumbai       12.0
1      Delhi           45   Delhi        7.0
2  Bangalore           30     NaN        NaN

In [18]:
df1 = pd.DataFrame({
    'city':['New York','Chicago','Orlando'],
    'temperature':[21,14,35]
})
df1

       city  temperature
0  New York           21
1   Chicago           14
2   Orlando           35

In [19]:
df2 = pd.DataFrame({
    'city':['New York','Chicago','Orlando'],
    'humidity':[65,68,75]
})
df2

       city  humidity
0  New York        65
1   Chicago        68
2   Orlando        75

In [21]:
df_merged = pd.merge(df1,df2, on="city")
df_merged

       city  temperature  humidity
0  New York           21        65
1   Chicago           14        68
2   Orlando           35        75

In [22]:
df1 = pd.DataFrame({
    'city':['New York','Chicago','Orlando','Baltimore'],
    'temperature':[21,14,35,38]
})
df1

        city  temperature
0   New York           21
1    Chicago           14
2    Orlando           35
3  Baltimore           38

In [23]:
df2 = pd.DataFrame({
    'city':['New York','Chicago','san diego'],
    'humidity':[65,68,75]
})
df2

        city  humidity
0   New York        65
1    Chicago        68
2  san diego        75

In [ ]:
# by default inner join ---> common values
pd.merge(df1,df2,on='city', how='inner')

       city  temperature  humidity
0  New York           21        65
1   Chicago           14        68

In [ ]:
# left join ---> all values in left df and the common values, but not the values from right df
pd.merge(df1,df2,on='city', how='left')

        city  temperature  humidity
0   New York           21      65.0
1    Chicago           14      68.0
2    Orlando           35       NaN
3  Baltimore           38       NaN

In [27]:
# right join ---> all values in right df and the common values, but not the values from left df
pd.merge(df1,df2,on='city', how='right')

        city  temperature  humidity
0   New York         21.0        65
1    Chicago         14.0        68
2  san diego          NaN        75

In [28]:
# outer join ---> all the values from both the df
pd.merge(df1,df2,on='city', how='outer')

        city  temperature  humidity
0  Baltimore         38.0       NaN
1    Chicago         14.0      68.0
2   New York         21.0      65.0
3    Orlando         35.0       NaN
4  san diego          NaN      75.0