In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('weather_by_cities.csv', parse_dates=['day'])
df

          day      city  temperature  windspeed   event
0  2017-01-01  new york           32          6    Rain
1  2017-01-02  new york           36          7   Sunny
2  2017-01-03  new york           28         12    Snow
3  2017-01-04  new york           33          7   Sunny
4  2017-01-01    mumbai           90          5   Sunny
5  2017-01-02    mumbai           85         12     Fog
6  2017-01-03    mumbai           87         15     Fog
7  2017-01-04    mumbai           92          5    Rain
8  2017-01-01     paris           45         20   Sunny
9  2017-01-02     paris           50         13  Cloudy
10 2017-01-03     paris           54          8  Cloudy
11 2017-01-04     paris           42         10  Cloudy

In [14]:
df['temp_by_cel'] = (df['temperature'].apply(lambda x:(x-32)/(9/5))).round(2)
df

          day      city  temperature  windspeed   event  temp_by_cel
0  2017-01-01  new york           32          6    Rain         0.00
1  2017-01-02  new york           36          7   Sunny         2.22
2  2017-01-03  new york           28         12    Snow        -2.22
3  2017-01-04  new york           33          7   Sunny         0.56
4  2017-01-01    mumbai           90          5   Sunny        32.22
5  2017-01-02    mumbai           85         12     Fog        29.44
6  2017-01-03    mumbai           87         15     Fog        30.56
7  2017-01-04    mumbai           92          5    Rain        33.33
8  2017-01-01     paris           45         20   Sunny         7.22
9  2017-01-02     paris           50         13  Cloudy        10.00
10 2017-01-03     paris           54          8  Cloudy        12.22
11 2017-01-04     paris           42         10  Cloudy         5.56

In [21]:
df[df.city == 'new york'].temp_by_cel.max()

np.float64(2.22)

In [23]:
g = df.groupby('city')
g

In [32]:
for city, data in g:
    print(f"City : {city}")
    print(type(city), type(data))
    print(data.temp_by_cel.max())

City : mumbai
<class 'str'> <class 'pandas.DataFrame'>
33.33
City : new york
<class 'str'> <class 'pandas.DataFrame'>
2.22
City : paris
<class 'str'> <class 'pandas.DataFrame'>
12.22

In [22]:
df.groupby('city')['temp_by_cel'].mean()

city
mumbai      31.3875
new york     0.1400
paris        8.7500
Name: temp_by_cel, dtype: float64

In [31]:
mumbai = g.get_group('mumbai')
type(mumbai)

pandas.DataFrame

In [33]:
g.max()

                day  temperature  windspeed  event  temp_by_cel
city
mumbai   2017-01-04           92         15  Sunny        33.33
new york 2017-01-04           36         12  Sunny         2.22
paris    2017-01-04           54         20  Sunny        12.22

In [38]:
g.describe()

           day                                                                 \
         count                 mean                  min                  25%
city
mumbai       4  2017-01-02 12:00:00  2017-01-01 00:00:00  2017-01-01 18:00:00
new york     4  2017-01-02 12:00:00  2017-01-01 00:00:00  2017-01-01 18:00:00
paris        4  2017-01-02 12:00:00  2017-01-01 00:00:00  2017-01-01 18:00:00

                                                                              \
                          50%                  75%                  max  std
city
mumbai    2017-01-02 12:00:00  2017-01-03 06:00:00  2017-01-04 00:00:00  NaN
new york  2017-01-02 12:00:00  2017-01-03 06:00:00  2017-01-04 00:00:00  NaN
paris     2017-01-02 12:00:00  2017-01-03 06:00:00  2017-01-04 00:00:00  NaN

         temperature         ... windspeed           temp_by_cel           \
               count   mean  ...       max       std       count     mean
city                         ...
mumbai           4.0  88.50  ...      15.0  5.057997         4.0  31.3875
new york         4.0  32.25  ...      12.0  2.708013         4.0   0.1400
paris            4.0  47.75  ...      20.0  5.251984         4.0   8.7500


            min     25%    50%      75%    max       std
city
mumbai    29.44  30.280  31.39  32.4975  33.33  1.726642
new york  -2.22  -0.555   0.28   0.9750   2.22  1.834121
paris      5.56   6.805   8.61  10.5550  12.22  2.950729

[3 rows x 32 columns]

In [39]:
g.size()

city
mumbai      4
new york    4
paris       4
dtype: int64

In [68]:
def grouper(df, idx, col):
    if 80 <= df[col].loc[idx] <= 90:
        return "80-90"
    elif 50 <= df[col].loc[idx] <= 60:
        return "50-60"
    else:
        return 'others'

In [69]:
g = df.groupby(lambda idx: grouper(df, idx, 'temperature'))

In [71]:
for key, data in g:
    print(f"Key : {key}")
    print(f"Data : \n{data}")

Key : 50-60
Data :
          day   city  temperature  windspeed   event  temp_by_cel
9  2017-01-02  paris           50         13  Cloudy        10.00
10 2017-01-03  paris           54          8  Cloudy        12.22
Key : 80-90
Data :
         day    city  temperature  windspeed  event  temp_by_cel
4 2017-01-01  mumbai           90          5  Sunny        32.22
5 2017-01-02  mumbai           85         12    Fog        29.44
6 2017-01-03  mumbai           87         15    Fog        30.56
Key : others
Data :
          day      city  temperature  windspeed   event  temp_by_cel
0  2017-01-01  new york           32          6    Rain         0.00
1  2017-01-02  new york           36          7   Sunny         2.22
2  2017-01-03  new york           28         12    Snow        -2.22
3  2017-01-04  new york           33          7   Sunny         0.56
7  2017-01-04    mumbai           92          5    Rain        33.33
8  2017-01-01     paris           45         20   Sunny         7.22
11 2017-01-04     paris           42         10  Cloudy         5.56