In [11]:
import pandas as pd

In [64]:
df = pd.read_csv('weather_data.csv')
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [6]:
type(df['day'][0])

str

In [65]:
df['day'] = pd.to_datetime(df['day'])
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [9]:
type(df['day'][0])

pandas.Timestamp

In [26]:
# or
df = pd.read_csv('weather_data.csv', parse_dates=['day'])
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [13]:
df.fillna(0, inplace=True)
df

TypeError: Invalid value '0' for dtype 'str'. Value should be a string or missing value, got 'int' instead.

In [23]:
print(df.dtypes)
df.fillna({
    'temperature': 0.0,
    'windspeed': 0.0,
    'event':"0"
}, inplace=True)
df

day            datetime64[us]
temperature           float64
windspeed             float64
event                     str
dtype: object

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          0.0        9.0   Sunny
2 2017-01-05         28.0        0.0    Snow
3 2017-01-06          0.0        7.0       0
4 2017-01-07         32.0        0.0    Rain
5 2017-01-08          0.0        0.0   Sunny
6 2017-01-09          0.0        0.0       0
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [30]:
# better way is to fill with mean/median values. best --> median 
# cause a large value can skew the mean.

df.fillna({
    'temperature': df.temperature.mean(),
    'windspeed': df.windspeed.mean(),
    'event': 'No event'
}, inplace=True)
df

         day  temperature  windspeed     event
0 2017-01-01        32.00       6.00      Rain
1 2017-01-04        33.22       9.00     Sunny
2 2017-01-05        28.00       8.42      Snow
3 2017-01-06        33.22       7.00  No event
4 2017-01-07        32.00       8.42      Rain
5 2017-01-08        33.22       8.42     Sunny
6 2017-01-09        33.22       8.42  No event
7 2017-01-10        34.10       8.10    Cloudy
8 2017-01-11        40.00      12.00     Sunny

In [31]:
df

         day  temperature  windspeed     event
0 2017-01-01        32.00       6.00      Rain
1 2017-01-04        33.22       9.00     Sunny
2 2017-01-05        28.00       8.42      Snow
3 2017-01-06        33.22       7.00  No event
4 2017-01-07        32.00       8.42      Rain
5 2017-01-08        33.22       8.42     Sunny
6 2017-01-09        33.22       8.42  No event
7 2017-01-10        34.10       8.10    Cloudy
8 2017-01-11        40.00      12.00     Sunny

In [36]:
# forward fill --> replacing nan values with forward value
df.ffill()

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         32.0        9.0   Sunny
2 2017-01-05         28.0        9.0    Snow
3 2017-01-06         28.0        7.0    Snow
4 2017-01-07         32.0        7.0    Rain
5 2017-01-08         32.0        7.0   Sunny
6 2017-01-09         32.0        7.0   Sunny
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [37]:
df.bfill()

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         28.0        9.0   Sunny
2 2017-01-05         28.0        7.0    Snow
3 2017-01-06         32.0        7.0    Rain
4 2017-01-07         32.0        8.1    Rain
5 2017-01-08         34.1        8.1   Sunny
6 2017-01-09         34.1        8.1  Cloudy
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [39]:
# Forward fill missing values, but fill at most 1 consecutive NaN 
df.ffill(limit=1)

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         32.0        9.0   Sunny
2 2017-01-05         28.0        9.0    Snow
3 2017-01-06         28.0        7.0    Snow
4 2017-01-07         32.0        7.0    Rain
5 2017-01-08         32.0        NaN   Sunny
6 2017-01-09          NaN        NaN   Sunny
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [40]:
df.bfill(limit=2)

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         28.0        9.0   Sunny
2 2017-01-05         28.0        7.0    Snow
3 2017-01-06         32.0        7.0    Rain
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08         34.1        8.1   Sunny
6 2017-01-09         34.1        8.1  Cloudy
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [ ]:
# interpolate() --> fill missing (NaN) values by estimating values between existing data points.
# cannot perform with strings
df.temperature.interpolate(method='linear')

0    32.0
1    30.0
2    28.0
3    30.0
4    32.0
5    32.7
6    33.4
7    34.1
8    40.0
Name: temperature, dtype: float64

In [47]:
df.windspeed.interpolate()

0     6.000
1     9.000
2     8.000
3     7.000
4     7.275
5     7.550
6     7.825
7     8.100
8    12.000
Name: windspeed, dtype: float64

In [49]:
# dropna ---> drop rows which consists null values
df.dropna()

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [50]:
df.dropna(how='any')

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [54]:
df.dropna(how='all',inplace=True)
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [55]:
df.isna()

     day  temperature  windspeed  event
0  False        False      False  False
1  False         True      False  False
2  False        False       True  False
3  False         True      False   True
4  False        False       True  False
5  False         True       True  False
6  False         True       True   True
7  False        False      False  False
8  False        False      False  False

In [57]:
import numpy as np
df.replace("NaN",np.nan, inplace=True)
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [ ]:
# even if one nan remove
df.dropna(thresh=1,inplace = True)
df

In [67]:
df1 = pd.read_csv("weather_data_1.csv")
df1

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

In [68]:
# in most of the finance companies, the nan values are represented as -99999.
# to replace that 

df1.replace(-99999,0)

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017            0          7     Sunny
2  1/3/2017           28          0      Snow
3  1/4/2017            0          7  no event
4  1/5/2017           32          0      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

In [71]:
# or 
df1.replace([-99999,-88888],np.nan)

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  no event
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0        NaN  no event

In [73]:
df1.replace({
    'temperature': -99999,
    'windspeed':[-99999,-88888],
    'event':"no event"
}, np.nan)

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        NaN    NaN

In [75]:
# also allows us to replace old value to new value
df1.replace({
    -99999:0,
    -88888:0,
    'no event': 'rainy'
})

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017            0          7  Sunny
2  1/3/2017           28          0   Snow
3  1/4/2017            0          7  rainy
4  1/5/2017           32          0   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          0  rainy